### ISSUE TITLE
MVP for 1.0.0.alpha1

### ISSUE THREAD

**Issue by manolo** [vaadin/vaadin-upload#1]
#### UX

- [x] Add files Button
- [x] Drop Area
- [x]  Multiple Upload
  - [x] Add files to Queue
  - [x] Remove files from Queue
  - [x] Abort Uploading (one/all item/s)
  - [x] Retry failed uploads
- [x] Detailed information what's happening
  - [x] Connecting with server
  - [x] Progress Bar and Info (%, ETA, bps)
  - [x] Server processing

#### Dev

- [x] XHR customization
 - [x] URI
 - [x] method
 - [x] headers
- [x] Custom error handler  (see below)
- [x] Events
 - [x] @event file-add
 - [x] @event upload-before
 - [x] @event upload-request
 - [x] @event upload-start
 - [x] @event upload-progress
 - [x] @event upload-response (used for custom error handler)
 - [x] @event upload-success
 - [x] @event upload-error
- [x] Auto-start upload

#### DoD

- Tests
  - [x] Unit tests
    - [x] Prepare Project and Travis.
    - [x] Cover all MVP cases
  - User tests
    - [x] links to documentation 
       [Ux Test checklist](https://docs.google.com/document/d/1ixmS3_WvBnYSpPLXLi4xCxTHPDJovhvEFUVKTNLe3WE/edit#heading=h.7fp1b6ajhn4y),
     [Scenarios](https://docs.google.com/document/d/1H56h26d4ypDVGfVW1-uYCz_0BhJqtaMp0HfBsnimFo4/edit#),
    - [x] Prepare and Deploy demos
        - [x] Live Servlet
        - [x] Live UX demos:  [desktop](http://wc.demo.vaadin.com/upload/vaadin-upload/ux/desktop.html),     [mobile](http://wc.demo.vaadin.com/upload/vaadin-upload/ux/mobile.html),

        - Run Tests and collect feedback
- Documentation
  - [x] API
  - Examples
  - [x] AsciiDoc

**Comment by manolo** [comment]
## Minimum Viable Product

-

**Comment by platosha** [comment]
A few agreements and planned steps as discussed with @manolo:

- Start new element from scratch.

- Do incremental commits in flavour of one big commit, in order to make it easier to review by other team members. Roughly one commit per MVP feature list point.

- API documentation and examples should be committed together with their related features, not afterwards

- @platosha starts from copying UX features from @manolo's prototype to the new element

- @manolo starts with setting up testing and adding tests
