### ISSUE TITLE
Safari: accept=.xls,.pdf attribute is not working correctly

### ISSUE THREAD

**Issue by manolo** [vaadin/vaadin-upload#56]
Seems that certain syntax for type validation is not working in Safari. 

Bug found in [UX testing](https://docs.google.com/document/d/12B7KE2PbWBKHO0JakMRcePo6bfD3jn5oiz0XrVl7FgI)

**Comment by platosha** [comment]
Safari doesn't support extension values (like `"*.xls"`) for `accept`. See: http://caniuse.com/#feat=input-file-accept

**Comment by jounik** [comment]
It seems like this might have been fixed in Safari 9.0.3

**Comment by jounik** [comment]
Is this limitation documented in our documentation (both asciidocs and api docs)?

**Comment by platosha** [comment]
API documentation doesn't mention this limitation.

Asciidoc does: “We rely on the [propertyname]#input.accept# specification to filter files in the file browser selector, but depending on the browser and system it might not work. Nevertheless, the component will validate files before sending them to the server.”

**Comment by platosha** [comment]
JSbin demo with raw <input type="file" accept=".pdf">: http://output.jsbin.com/tejiqozuvo

**Comment by platosha** [comment]
Nikolay G. found the similar issue in Android Browser (not in the supported platforms list): `accept=".pdf"` gives an error message like “No application for this action” instead of opening select file options. Works fine in Chrome on Android.

I think we should get rid of `accept=".pdf"` mentions in our documentation and advice developers against using it in favour of `"application/pdf"` mime type notation.

**Comment by jounik** [comment]
Documentation task: #89
